version: "3.8"

services:
    database:
        container_name: "db_mysql"
        image: "mysql:latest"
        restart: unless-stopped
        ports:
            - "33060:3306"
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    cache:
        container_name: "redis"
        image: "redis:7.0.3"
        restart: unless-stopped
        ports:
            - "33970:6379"
